/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 ./public/davinci.glb
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/davinci.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="6°_Letra" rotation={[Math.PI / 2, -1.396, Math.PI]}>
          <mesh name="Cylinder" geometry={nodes.Cylinder.geometry} material={materials['Material.001']} />
          <mesh name="Cylinder_1" geometry={nodes.Cylinder_1.geometry} material={materials['Material.002']} />
          <mesh name="Cylinder_2" geometry={nodes.Cylinder_2.geometry} material={materials['Material.002']} />
        </group>
        <group name="Abertura" position={[0, 0, 0.016]} rotation={[Math.PI / 2, 0, Math.PI]}>
          <mesh name="Cylinder001" geometry={nodes.Cylinder001.geometry} material={materials['Material.001']} />
          <mesh name="Cylinder001_1" geometry={nodes.Cylinder001_1.geometry} material={materials['Material.002']} />
        </group>
        <group name="Fixo" rotation={[Math.PI / 2, 0, Math.PI]}>
          <mesh name="Cylinder002" geometry={nodes.Cylinder002.geometry} material={materials['Material.001']} />
          <mesh name="Cylinder002_1" geometry={nodes.Cylinder002_1.geometry} material={materials['Material.002']} />
        </group>
        <group name="1°_letra" rotation={[Math.PI / 2, -1.396, Math.PI]}>
          <mesh name="Cylinder003" geometry={nodes.Cylinder003.geometry} material={materials['Material.001']} />
          <mesh name="Cylinder003_1" geometry={nodes.Cylinder003_1.geometry} material={materials['Material.002']} />
          <mesh name="Cylinder003_2" geometry={nodes.Cylinder003_2.geometry} material={materials['Material.002']} />
          <mesh name="Cylinder003_3" geometry={nodes.Cylinder003_3.geometry} material={materials['Material.002']} />
        </group>
        <group name="2°letra" rotation={[Math.PI / 2, -1.396, Math.PI]}>
          <mesh name="Cylinder004" geometry={nodes.Cylinder004.geometry} material={materials['Material.001']} />
          <mesh name="Cylinder004_1" geometry={nodes.Cylinder004_1.geometry} material={materials['Material.002']} />
          <mesh name="Cylinder004_2" geometry={nodes.Cylinder004_2.geometry} material={materials['Material.002']} />
        </group>
        <group name="3°_Letra" rotation={[Math.PI / 2, -1.396, Math.PI]}>
          <mesh name="Cylinder005" geometry={nodes.Cylinder005.geometry} material={materials['Material.001']} />
          <mesh name="Cylinder005_1" geometry={nodes.Cylinder005_1.geometry} material={materials['Material.002']} />
          <mesh name="Cylinder005_2" geometry={nodes.Cylinder005_2.geometry} material={materials['Material.002']} />
          <mesh name="Cylinder005_3" geometry={nodes.Cylinder005_3.geometry} material={materials['Material.002']} />
        </group>
        <group name="4°_Letra" rotation={[Math.PI / 2, -1.396, Math.PI]}>
          <mesh name="Cylinder006" geometry={nodes.Cylinder006.geometry} material={materials['Material.001']} />
          <mesh name="Cylinder006_1" geometry={nodes.Cylinder006_1.geometry} material={materials['Material.002']} />
          <mesh name="Cylinder006_2" geometry={nodes.Cylinder006_2.geometry} material={materials['Material.002']} />
        </group>
        <group name="5°_Letra" rotation={[Math.PI / 2, -1.396, Math.PI]}>
          <mesh name="Cylinder007" geometry={nodes.Cylinder007.geometry} material={materials['Material.001']} />
          <mesh name="Cylinder007_1" geometry={nodes.Cylinder007_1.geometry} material={materials['Material.002']} />
          <mesh name="Cylinder007_2" geometry={nodes.Cylinder007_2.geometry} material={materials['Material.002']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/davinci.glb')
